### ISSUE TITLE
Fix structured metadata script tag

### ISSUE THREAD

**Issue by aidanatwork** [thegooddocsproject/incubator#21]
script tag for structured data is rendering to the page and probably not crawlable. need to wrap it in curly braces and add instructions to the user telling them to add this tag to their page HTML.

**Comment by camerons** [comment]
Aidan, I was looking at Choco's [logging template](https://raw.githubusercontent.com/thegooddocsproject/templates/master/logging/template-logging.md), and the front matter that I believe we are going to have in our future markdown, and I wonder whether this front mater could be auto-converted into JSON-LD during the publishing process?
This might get around the poor rendering of metadata in github, and still keep the metadata in the final doc.

**Comment by aidanatwork** [comment]
Just merged my fix for this issue into Cameron's branch, so I'm going to close this issue out.
